# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

settings = YAML.load_file 'vagrant.yml'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
 
Vagrant.configure("2") do |config|
  config.vm.define "devimage" do |a|
    a.vm.provider "docker" do |d|
      d.build_dir = "../docker/devimage"
      d.build_args = ["-t=devimage"]
      d.ports = ["8080:8080","8000:8000","80:80","443:443","2222:22"]
      d.volumes = ["/home/developer/api_project:/home/developer/api_project","/home/developer/web_project:/home/developer/web_project","/usr/local/tomcat/webapps:/usr/local/tomcat/webapps","/var/www/apps/localhost/dist:/var/www/apps/localhost/dist","/home/developer/.gradle:/home/developer/.gradle"]
      d.name = "letssgdev"
      d.cmd = ["/run.sh"]
      d.vagrant_machine = "dockerhost"
      d.vagrant_vagrantfile = "./DockerHostVagrantfile"
    end
  end
end
