#!/usr/bin/env groovy
import hudson.model.*
import hudson.EnvVars
import java.net.URL

err = null
currentVersion = null
isLocal = false
repo_url = ""
repo_protocol = ""
proceed = ""
buildingPR = false
def getUser(fie){
    if (fie.causes.size() > 0) {
        def user = fie.causes[0].user
        return user;
    }
}

def getMSInfo(){
    sh '''
        mvn -q -Dexec.executable="echo" -Dexec.args='${project.distributionManagement.repository.url}' --non-recursive exec:exec >/tmp/NEXUS
        mvn -q -Dexec.executable="echo" -Dexec.args='${project.groupId}' --non-recursive exec:exec >/tmp/GROUPID
        mvn -q -Dexec.executable="echo" -Dexec.args='${project.artifactId}' --non-recursive exec:exec >/tmp/ARTIFACTID
        mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec >/tmp/MVN_VERSION
    '''
    artifactId = readFile('/tmp/ARTIFACTID').trim()
    echo "Service Name: "+artifactId
    mavenVersion = readFile('/tmp/MVN_VERSION').trim()
    echo "Maven Version : "+mavenVersion
    NEXUS = readFile('/tmp/NEXUS').trim()
    echo "NEXUS URL: "+NEXUS
    GROUPID = readFile('/tmp/GROUPID').trim().replaceAll("\\.","/")
    echo "GROUPID: "+GROUPID

}
def checkOut() {
    checkout scm

    isLocal = true
    sh 'git status'
    sh 'git config --get remote.origin.url >/tmp/giturl.txt'
    sh 'git rev-parse --abbrev-ref HEAD > /tmp/GIT_BRANCH'
    git_branch = readFile('/tmp/GIT_BRANCH').trim()
    echo "Git Branch: "+git_branch
    echo "Checked out branch "+ git_branch
    def lines = readFile('/tmp/giturl.txt').split("\r?\n")
    gitUrl = lines[0]
    echo "Git URL :" + gitUrl
    buildingPR = true
    try {
        echo "TO_BRANCH=${TO_BRANCH} , FROM_BRANCH=${FROM_BRANCH}"
    } catch (groovy.lang.MissingPropertyException e) {
        buildingPR = false
    }
    if (gitUrl.contains("http://") || gitUrl.contains("https://")){
        isLocal = false
        def url = new URL(gitUrl)
        if (url.getPort() >0){
            repo_url = url.getHost()+":"+url.getPort()+url.getPath()
        }else{
            repo_url = url.getHost()+url.getPath()
        }
        repo_protocol = url.getProtocol()

    }

    if (!isLocal && buildingPR){
        echo "Building Pull Request"
        //checkout changelog: true, poll: true, scm: [$class: 'GitSCM', branches: [[name: '${git_branch}']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'PreBuildMerge', options: [fastForwardMode: 'FF', mergeRemote: 'origin', mergeTarget: "${TO_BRANCH}"]]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '8edec322-14b9-4321-b27a-2ebd8b5ea3d3', url: "${gitUrl}"]]]
        checkout changelog: true, poll: true, scm: [$class: 'GitSCM', branches: [[name: "${git_branch}"]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'PreBuildMerge', options: [fastForwardMode: 'FF', mergeRemote: 'origin',  mergeTarget: "${TO_BRANCH}"]], [$class: 'DisableRemotePoll'], [$class: 'WipeWorkspace']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '8edec322-14b9-4321-b27a-2ebd8b5ea3d3', url: "${gitUrl}"]]]

        echo "Merged ${FROM_BRANCH} with ${git_branch}"

    }
    return isLocal

}


@NonCPS
def populateEnv(){ binding.variables.each{k,v -> env."$k" = "$v"} }
def getBranchName(){
    return git_branch
}
def getCurrentVersion(release){
    def version = "<version>"+mavenVersion+"</version>"
    echo version
    def matcher = release ?  version =~ '<version>(.*?)(-SNAPSHOT)*</version>' : version =~ '<version>(.*)</version>'
    echo matcher[0][1].toString()
    matcher[0] ? matcher[0][1] : null
}

def getNextVersion(){
    def version = "<version>"+mavenVersion+"</version>"
    def matcher = version =~ '<version>(\\d*)\\.(\\d*)\\.(\\d*)(-SNAPSHOT)*</version>'
    echo matcher[0].toString()
    if (matcher[0]){
        def original = matcher[0]
        echo original[3]
        def major = original[1];
        def minor = original[2];
        def patch  = Integer.parseInt(original[3]) + 1;
        def v = "${major}.${minor}.${patch}"
        v ? v : null
    }
}
def updateChefCookbookVersion(oldversion, newversion){
    metadataFile = 'chef/cookbooks/'+artifactId+"/metadata.rb"
    cookbookVersion = "version          '"+oldversion+"'"
    cookbookNewVersion = "version          '"+newversion+"'"

    def attributesFile =  'chef/cookbooks/'+artifactId+'/attributes/default.rb'
    artifactVersion= "default\\['"+artifactId+"'\\]\\['artifact'\\]\\['version'\\] = \""+newversion+"\""
    oldArtifactVersion= "default\\['"+artifactId+"'\\]\\['artifact'\\]\\['version'\\] = \""+oldversion+"\""
    artifactRepo = "default\\['"+artifactId+"'\\]\\['repo'\\]"
    artifactNewRepo = "default['"+artifactId+"']['repo']='"+NEXUS+"/"+GROUPID+"/'"
    echo artifactVersion
    populateEnv();
    withEnv(["ATTRIBUTESFILE=${attributesFile}"]){
        sh '''
            ls -ltr
            set
            sed -i "/$artifactRepo/d" $ATTRIBUTESFILE
            sed -i "s/$oldArtifactVersion/$artifactVersion/" $ATTRIBUTESFILE
            echo $artifactNewRepo >> $ATTRIBUTESFILE
            sed -i "s/$cookbookVersion/$cookbookNewVersion/" $metadataFile

        '''
    }
    def lines = readFile(attributesFile)
    echo lines.toString()

}
def uploadCookbook(){
    sh '''
        cd chef/cookbooks
        knife cookbook upload $artifactId
    '''
}
def build(){
    unstash 'source'
    sh '''
        export JAVA_HOME=/usr/bin/jdk8
        chmod +x src/test/scripts/run.sh
        export MAVEN_OPTS="-Xmx2048m -Xms1024m -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
        mvn -q -B -f pom.xml clean compile
    '''


}
def unitTests(){
    sh '''
      export MAVEN_OPTS="-Xmx2048m -Xms1024m -XX:+TieredCompilation -XX:TieredStopAtLevel=1 "
      export JAVA_HOME=/usr/bin/jdk8
      mvn -q -f pom.xml  clean compile  verify install -Dmaven.test.failure.ignore=true
    '''
    archive '**/*.jar'
    step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
}
def staticAnalysis(){
    sh '''
      mvn -X -B -f pom.xml findbugs:check -Dmaven.findbugs.skip=false
      mvn -q -B -f pom.xml pmd:check -Dmaven.pmd.skip=false
      mvn --quiet -B -f pom.xml checkstyle:check -Dmaven.checkstyle.skip=false
    '''
    step([$class: 'PmdPublisher', canComputeNew: false, canRunOnFailed: true, defaultEncoding: '', healthy: '', pattern: '', shouldDetectModules: true, unHealthy: ''])
    step([$class: 'CheckStylePublisher', canComputeNew: false, canRunOnFailed: true, defaultEncoding: '', healthy: '', pattern: '', shouldDetectModules: true, unHealthy: ''])
    step([$class: 'FindBugsPublisher', canComputeNew: false, canRunOnFailed: true, defaultEncoding: '', excludePattern: '', healthy: '', includePattern: '', pattern: '**/findbugsXml.xml', shouldDetectModules: true, unHealthy: ''])
    step([$class: 'AnalysisPublisher', canComputeNew: false, canRunOnFailed: true, defaultEncoding: '', healthy: '', unHealthy: ''])
}
def acceptanceTests(currentVersion){
    withEnv(["VERSION_IN_POM=${currentVersion}"]){
        sh '''
          chmod +x docker/run.sh
          export DOCKER_API_VERSION=1.22
          export JAVA_HOME=/usr/bin/jdk8
          export APP_IP=172.17.0.1
          echo $JAVA_HOME
          #mvn verify -Pacceptance-tests -Dmaven.test.failure.ignore=true
        '''

    }
    step([$class: 'CucumberReportPublisher', fileExcludePattern: '', fileIncludePattern: '**/cucumber*.json', ignoreFailedTests: false, jenkinsBasePath: '', jsonReportDirectory: '', missingFails: false, parallelTesting: false, pendingFails: false, skippedFails: false, undefinedFails: false])
}



def pushToGit(){
    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: '8edec322-14b9-4321-b27a-2ebd8b5ea3d3', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD']]) {

        sh('git push --force ${repo_protocol}://${GIT_USERNAME}:${GIT_PASSWORD}@${repo_url}  ')
    }
}
def pushTagsToGit(){
    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: '8edec322-14b9-4321-b27a-2ebd8b5ea3d3', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD']]) {
        sh('git push --force ${repo_protocol}://${GIT_USERNAME}:${GIT_PASSWORD}@${repo_url}  --tags')
    }
}

def deploy(){
    echo "Deploying on Test via Chef"
}
def release(){
    checkOut()
    nextVersion = getNextVersion();
    def BRANCH_NAME = getBranchName()
    populateEnv()
    withEnv(["VERSION_IN_POM=${versionInPOM}"]){
        sh '''
            mvn -q versions:set -DnewVersion=$VERSION_IN_POM -DgenerateBackupPoms=false
            git add pom.xml
            git status
            git config --global user.email "esb_btb@aib.ie"
            git config --global user.name "esb_btb"
            git commit -a -m "Bumped version number to $VERSION_IN_POM"
            git status
            git tag -f -a v$VERSION_IN_POM -m "Version $VERSION_IN_POM"
        '''
    }
    withEnv(["VERSION_IN_POM=${versionInPOM}"]){
        sh '''
            export JAVA_HOME=/usr/bin/jdk8
            cp /home/jenkins/tmp/m2/settings*xml /home/jenkins/.m2
            mvn -q  deploy -Dmaven.test.skip=true
        '''
    }
    uploadCookbook()
    pushToGit()
    pushTagsToGit()
    updateChefCookbookVersion(versionInPOM,nextVersion)
    sh '''
        mvn -q versions:set  -DgenerateBackupPoms=false  -DnewVersion=${nextVersion}-SNAPSHOT
        git commit -a -m "Set version number to ${nextVersion}-SNAPSHOT"
    '''
    pushToGit()
    currentBuild.displayName = versionInPOM
    currentBuild.description = "Released Version "+versionInPOM
}
def verifyCookbook(){
    echo "Verifying Cookbook"

}
def ask(question,timevalue, timeunit){
    def timedOut = false
    def aborted = false
    try {
        timeout(time: timevalue, unit: timeunit) { // change to a convenient timeout for you
            userInput = input(id: 'Proceed1', message: question, parameters: [])
        }
    } catch (org.jenkinsci.plugins.workflow.steps.FlowInterruptedException fie) {
        // timeout reached or input false
        def user = getUser(fie)
        if ('SYSTEM' == user.toString()) { // SYSTEM means timeout.
            timedOut = true
            currentBuild.result = "FAILED"
        } else {
            aborted = true
            echo "Aborted by: [${user}]"
            currentBuild.result = "ABORTED"
        }


    }
    if (timedOut || aborted){
        return false
    }
    return true;
}
node {
    try {
        wrap([$class: 'AnsiColorBuildWrapper']) {
            try {
                node("master") {
                    stage "\u2776 Checkout"
                    isLocal = checkOut()
                    stash excludes: '**/target', includes: '**', name: 'source'
                }
                node("dsf-jenkins-slave") {
                    stage "\u2777 Build"
                    build()
                    stage '\u2778 Unit/Integration Tests'
                    unitTests()
                    stage '\u2779 Static Analysis'
                    staticAnalysis()
                    stage '\u277A Acceptance Tests'
                    getMSInfo()
                    versionInPOM = getCurrentVersion(false)
                    acceptanceTests(versionInPOM)
                    if (!buildingPR){
                        stage '\u277B Verify Chef Cookbook'
                        verifyCookbook()
                    }
                    if (!isLocal && !buildingPR){
                        stage '\u277C Release'
                        versionInPOM = getCurrentVersion(true)
                        proceed = ask('Do you want to release version ' + versionInPOM + ' to nexus?', 1, "HOURS")


                    }
                }
                if (proceed) {
                    node("dsf-jenkins-slave") {
                        release()
                        stage '\u277D Deploy on Test'
                        def proceed_deploy = ask('Do you want to deploy version ' + versionInPOM + ' to Test?', 1, "MINUTES")
                        if (proceed_deploy){
                            deploy()
                        }
                    }

                }//end proceed

            } catch (caughtError) {
                err = caughtError
                currentBuild.result = "FAILURE"
            }
        }
    } finally {
        (currentBuild.result != "ABORTED") && node("master") {
            // Send e-mail notifications for failed or unstable builds.
            // currentBuild.result must be non-null for this step to work.
            /*step([$class: 'Mailer',
              notifyEveryUnstableBuild: true,
              recipients: "${email_to}",
              sendToIndividuals: true])*/
        }

        // Must re-throw exception to propagate error:
        if (err) {
            throw err
        }
    }
}
