# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

settings = YAML.load_file 'vagrant.yml'
home_folder = ENV['HOME']
dev_uid = Process.uid
gradle_folder = home_folder+"/.gradle"
api_src_folder = home_folder+"/api_project"
web_src_folder = home_folder+"/web_project"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
 
Vagrant.configure("2") do |config|
  config.vm.define "devimage" do |a|
    a.vm.provider "docker" do |d|
      d.build_dir = "../../docker/devimage/"
      d.env = {"DEV_UID"=>dev_uid,"USERNAME"=>settings['user']['name'],"HOME_FOLDER"=>home_folder}
      d.build_args = ["-t=devimage"]
      d.force_host_vm = true
      d.ports = ["8080:8080","8000:8000","80:80","443:443","2222:22"]
      d.volumes = [gradle_folder+":"+gradle_folder,api_src_folder+":"+api_src_folder,web_src_folder+":"+web_src_folder,"/var/www/apps/localhost/dist:/var/www/apps/localhost/dist"]
      d.name = "development"
      d.cmd = ["/run.sh"]
      d.vagrant_machine = "dockerhost"
      d.vagrant_vagrantfile = "./DockerHostVagrantfile"
    end
  end
end
